name: barcode_flutter_demo
description: Demo project for the Flutter Barcode library.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  barcode_flutter:
    path: ..
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.1
